Remove default responses from nanomaterials
OfficeForProductSafetyAndStandards/cosmetic-product-notifications pull request #2868
Opened 2023-03-28 12:12 UTC by tobyprivett

https://regulatorydelivery.atlassian.net/browse/COSBETA-1859

## Description
If a notification does *not* contain nano materials, then we remove the
`contains_nanomaterials` question from the notification's `routing_questions_answers`

Here we also fix an incorrect validation error message:
'mulit-item kit' was displayed, instead of 'nanomaterial'

Testing note: You will need to create a notification manually, and clone that.
If you clone a notification that was created with seed data, the 
`new_notification.routing_questions_answers` attribute won't be set properly,

## Review apps

https://cosmetics-pr-2868-submit-web.london.cloudapps.digital/

2023-03-28 14:19 UTC, rubenarakelyan requested changes

2023-03-28 14:19 UTC, rubenarakelyan commented on cosmetics-web/app/services/notification_cloner/base.rb
> +        new_notification.routing_questions_answers[:contains_nanomaterials] = nil
We should always set this to `nil` since we always want the user to choose.

2023-03-28 14:48 UTC, tobyprivett commented on cosmetics-web/app/services/notification_cloner/base.rb
> +        new_notification.routing_questions_answers[:contains_nanomaterials] = nil
In this instance, they want this to only apply when the are no nanomaterials:
"Where my original notification did not contain a nanomaterial, the radio buttons will not default to my original response, and I will be required to select “Yes “ or “No” in answer to this question"
and 
"When I access SCPN and I clone a previously submitted notification for my organisation which contained a nanomaterial, current behaviour and functionality will remain as-is"
@rubenarakelyan

2023-03-29 08:39 UTC, rubenarakelyan commented on cosmetics-web/app/services/notification_cloner/base.rb
> +        new_notification.routing_questions_answers[:contains_nanomaterials] = nil
Ah, I must have misunderstood

2023-03-29 08:39 UTC, rubenarakelyan approved these changes

2023-03-29 11:21 UTC, nasirkhanbeis approved these changes
Tested this along with Andre and happy. working as expected.

2023-03-31 15:13 UTC, merged