Remove “upload ingredients using CSV file” link
OfficeForProductSafetyAndStandards/cosmetic-product-notifications pull request #2897
Opened 2023-04-14 12:52 UTC by rubenarakelyan

## Description

This link is not required since the user makes the choice to upload a CSV file on the screen prior to the screen on which the link is displayed.

## JIRA ticket(s)

https://regulatorydelivery.atlassian.net/browse/COSBETA-1883

## Screenshots/video

### Before

![Screenshot 2023-04-14 at 13 52 15](https://user-images.githubusercontent.com/444232/232048759-8c5c9e85-53cf-4f13-9cd1-cd5db9231ee4.png)

### After

![Screenshot 2023-04-14 at 13 51 52](https://user-images.githubusercontent.com/444232/232048781-179d5c5b-12fa-4ea1-a401-7db1a847e5a6.png)

## Review apps

https://cosmetics-pr-xxxx-submit-web.london.cloudapps.digital/
https://cosmetics-pr-xxxx-search-web.london.cloudapps.digital/

## Checklist

- [x] All automated checks are passing locally (tests, linting etc)
- [ ] Accessibility testing has been done (where appropriate)
  - [ ] Usable with JavaScript off
  - [ ] Usable with CSS off
  - [ ] Usable on a small screen (e.g. mobile phone)
  - [ ] Usable with just a keyboard
  - [ ] Usable with a screen reader
  - [ ] Usable at 400% zoom
- [x] Automated tests have been added or updated
- [ ] Documentation has been added or updated
- [ ] Database seeds have been updated
- [ ] Database migrations have been tested (both up and down) and are safe (e.g. stop using a column before removing it)
- [ ] A feature flag has been added (if required in the ticket; a ticket has also been added to remove the feature flag once deployment is completed)
- [ ] Comms have been sent to users (if required in the ticket)

## Post-deploy tasks

No

2023-04-14 14:51 UTC, acallaghan approved these changes

2023-04-17 08:51 UTC, tobyprivett approved these changes

2023-04-17 12:10 UTC, kress2m1 requested changes
Search is broken. When you select search without entering a text, it brings back the results of the newly created product. When text is entered into the search filed, a 500 error is returned

2023-04-18 10:28 UTC, kress2m1 approved these changes
Approved

2023-04-19 14:24 UTC, merged