fix/PSD-3973-SCPN-phone_number_not_valid
OfficeForProductSafetyAndStandards/cosmetic-product-notifications pull request #3474
Opened 2024-11-28 16:34 UTC by mirotriad

#### **Issue**
The system encountered a `ValidationError` when sending SMS for OTP delivery. The error occurred due to inconsistent handling and validation of phone numbers, resulting in the rejection of valid numbers and failed authentication attempts.

#### **Changes Introduced**
1. **Added Phone Number Validation:**
   - Integrated the `Phonelib` gem to validate and format phone numbers.
   - Implemented a method to sanitise input phone numbers by stripping unnecessary characters and ensuring proper formatting.
   - Introduced logic to handle invalid numbers gracefully by raising an appropriate error.

2. **Updated Tests:**
   - Replaced hardcoded invalid phone numbers in tests with valid UK-format numbers (`+447500000000`).
   - Enhanced test coverage to check the handling of both valid and invalid phone numbers.
   - Verified proper sanitisation and formatting during SMS authentication setup.

3. **Improved SMS Sending Logic:**
   - Adjusted the SMS service to validate and format phone numbers before sending.
   - Added error handling to prevent invalid phone numbers from being passed to the `Notifications::Client`.

4. **Gemfile Updates:**
   - Added `Phonelib` to the project dependencies for robust phone number handling.

5. **Refactored Code:**
   - Introduced methods for sanitisation (`sanitize_number`) and validation (`validate_and_format_number`) in the `SendSubmitSms` service.

#### **Testing**
- Manually tested with various phone number formats (international, local, and invalid).
- Ensured that valid numbers are accepted and invalid numbers raise meaningful errors.
- Verified changes with updated test cases to maintain expected functionality across the application.

#### **Impact**
- Improved reliability of the SMS authentication process by ensuring phone numbers are correctly validated and formatted.
- Reduced user errors and enhanced the experience by supporting a wider range of valid phone number formats.

#### **Files Changed**
1. **Gemfile** - Added `Phonelib` gem dependency.
2. **SendSubmitSms Service** - Added sanitisation and validation logic.
3. **Test Files** - Updated tests to reflect new validation and ensure proper handling.

2024-11-28 16:58 UTC, meeravnagesh requested changes

2024-11-28 16:58 UTC, meeravnagesh commented on cosmetics-web/spec/factories/user.rb
> -      mobile_number { "07500 000 000" }
what will happen if the User does give the number 07500 000 000 on the screen , will the code not handle it ?

2024-11-28 16:58 UTC, meeravnagesh commented on cosmetics-web/app/services/send_submit_sms.rb
> +    valid_number = validate_and_format_number(mobile_number)
Venu recently worked on this area in PSD, ask him all the different inputs that he tried and make sure your code handles all those inputs.

2024-11-28 16:58 UTC, meeravnagesh commented on cosmetics-web/Gemfile
> +gem "phonelib", "~> 0.7"
why this cant be gem "phonelib", "~> 0.10.1" , any reason

2024-11-28 17:10 UTC, mirotriad commented on cosmetics-web/Gemfile
> +gem "phonelib", "~> 0.7"
Good point. I'll update to version 0.10, but should we specify exactly 0.10.1 or should we allow updates withing 0.10.x by using "phonelib", "~> 0.10" ?

2024-11-29 13:55 UTC, mirotriad commented on cosmetics-web/Gemfile
> +gem "phonelib", "~> 0.7"
The gemfile is now updated to take the current latest version of phonelib.

2024-11-29 13:55 UTC, mirotriad commented on cosmetics-web/spec/factories/user.rb
> -      mobile_number { "07500 000 000" }
According to my understanding and testing, it should handle it. The reason this was updated is because phonelib doesn't accept this format, but in the app numbers goes through sanitize_number method which should accept all valid numbers and pass them to phonelib in its accepted format. Perhaps we could further improve tests, but that might be beyond scope of this ticket.

2024-11-29 14:03 UTC, mirotriad commented on cosmetics-web/app/services/send_submit_sms.rb
> +    valid_number = validate_and_format_number(mobile_number)
I've updated the code to ensure all cases are accepted (only exception is perhaps 040-) - including international numbers. In the future we should consider adding country code as a mandatory requirement.

2024-12-02 14:04 UTC, mirotriad commented on cosmetics-web/app/services/send_submit_sms.rb
> +    valid_number = validate_and_format_number(mobile_number)
I've added comprehensive testing into cosmetics-web/spec/services/send_submit_sms_spec.rb to check with number of difference valid and invalid inputs, and then further improved the code.

2024-12-02 14:49 UTC, meeravnagesh approved these changes

2024-12-03 14:54 UTC, merged