perf/PSD-3232-SCPN-product_controler_refactoring
OfficeForProductSafetyAndStandards/cosmetic-product-notifications pull request #3498
Opened 2024-12-17 15:30 UTC by mirotriad

# Optimize Performance of Product Controller's Show and Update Methods

## Summary
This PR improves the performance of the `ResponsiblePersons::Notifications::ProductController` by optimizing database queries in both `show` and `update` methods. The changes reduce unnecessary database loads and minimize query count while maintaining existing functionality.

## Key Changes

### Show Method Optimization
- Reduced query count from 4+ to 1-3 queries for the completed step
- Implemented selective association loading based on the current step
- Added performance test to ensure query count stays within acceptable limits

### Update Method Optimization
- Reduced query count from 4+ to 2 queries for simple updates
- Added direct column updates using `update_column` for simple attribute changes:
  - `product_name` updates
  - `under_three_years` updates
- Implemented selective association loading in `set_notification_and_authorize`:
  - Only loads `nano_materials` and `components` for steps that need them
  - Only loads `components` for the `single_or_multi_component` step
  - No association loading for simple updates

### Code Organization
- Improved code maintainability by organizing related operations
- Added database transactions for atomic operations
- Added performance tests to prevent query count regression

## Performance Improvements
- Simple updates (e.g., product name changes): Reduced from 4+ to 2 queries
- Show method completed step: Reduced to maximum 3 queries
- Eliminated unnecessary association loading for steps that don't need them

## Testing
- Added performance-specific tests to monitor query count
- All existing functionality tests remain passing
- New tests ensure query counts stay within expected limits

## Notes
- No changes to existing business logic or validation rules
- Maintains all security checks and authorization flows
- Backwards compatible with existing API contracts

2024-12-17 15:57 UTC, meeravnagesh requested changes

2024-12-17 15:57 UTC, meeravnagesh commented on cosmetics-web/app/controllers/responsible_persons/notifications/product_controller.rb
> +        success ? render_next_step(@notification) : rerender_current_step
could you please let me know what will happen when you re render current step when its a failure?
and instead of success use a more apt variable name -like  column_updated

2024-12-17 16:34 UTC, mirotriad commented on cosmetics-web/app/controllers/responsible_persons/notifications/product_controller.rb
> +        success ? render_next_step(@notification) : rerender_current_step
Thanks for the feedback @meeravnagesh! I've made the following improvements:

1. Renamed the variable from `success` to `column_updated` to better describe what it represents.

2. Regarding what happens on failure (when rerendering current step):
   - Previously, the form would be re-rendered without any indication of what went wrong
   - I've improved this by adding explicit error messages to the notification's errors collection
   - Now when an update fails, the user will see an error message explaining that the field could not be updated
   - The error will be displayed in the form, allowing the user to understand what went wrong and try again

The changes make the error handling more user-friendly while maintaining the same functionality. Let me know if you'd like me to make any additional improvements!

2024-12-17 17:33 UTC, mirotriad commented on cosmetics-web/app/controllers/responsible_persons/notifications/product_controller.rb
> +      .select("notifications.*, responsible_persons.id as responsible_person_id, responsible_persons.name as responsible_person_name")
You're absolutely right about the performance implications. Using explicit column selection instead of wildcards is more performant for several reasons:

1. Reduced network bandwidth - only required columns are transferred
2. Lower memory usage - application only loads needed data
3. Better query optimization - database can optimize based on exact columns needed
4. Future-proofing - new columns won't automatically be included

This is especially important in our case since:
- We're joining with the responsible_persons table
- The notifications table has many columns but we only need specific ones
- These columns are actively used in various controller actions

I've updated the code to explicitly list all required columns. Let me know if you think we should add or remove any columns from the selection.

2024-12-18 15:19 UTC, tahir-khalid approved these changes

2024-12-19 10:29 UTC, meeravnagesh commented on cosmetics-web/app/controllers/responsible_persons/notifications/product_controller.rb
>        if params[:back_to_edit] == "true"
line 246 to 252 is not needed as you have handled that in handle_existing_image_uploads , right ?

2024-12-19 10:42 UTC, mirotriad commented on cosmetics-web/app/controllers/responsible_persons/notifications/product_controller.rb
>        if params[:back_to_edit] == "true"
Yes, you are absolutely right - handle_existing_image_upload already does the same. I've now fixed this - [Remove duplicated image upload handling code in favor of handle_exist…](https://github.com/OfficeForProductSafetyAndStandards/cosmetic-product-notifications/pull/3498/commits/b9651ca39cd41ba1b1445a67ab7f722c488ac84f)

2024-12-19 10:51 UTC, meeravnagesh commented on cosmetics-web/app/controllers/responsible_persons/notifications/product_controller.rb
> +      if notification_params.key?(:product_name)
extract the duplicate code into a method and send in params to the method

2024-12-19 10:55 UTC, meeravnagesh commented on cosmetics-web/app/controllers/responsible_persons/notifications/product_controller.rb
> +      elsif notification_params.key?(:under_three_years)
if else if , can this be a switch case?

2024-12-19 11:01 UTC, meeravnagesh commented on cosmetics-web/app/controllers/responsible_persons/notifications/product_controller.rb
> +        @notification.update_column(:industry_reference, nil)
before it was not updated , but now we are updating the industry _reference to the db  as nil ? is this needed

2024-12-19 11:04 UTC, meeravnagesh commented on cosmetics-web/app/controllers/responsible_persons/notifications/product_controller.rb
> +        if @notification.update_with_context(notification_params, step)
line 194 to 198 . can this be replaced by your method update_with_context_and_render

2024-12-19 11:05 UTC, meeravnagesh commented on cosmetics-web/app/controllers/responsible_persons/notifications/product_controller.rb
> +    @notification.transaction do
do we need a Transaction here, does   @notification.make_single_ready_for_components!(form.components_count.to_i) is saving data to database?

2024-12-19 11:07 UTC, meeravnagesh commented on cosmetics-web/app/controllers/responsible_persons/notifications/product_controller.rb
> +      @notification.transaction do
it should be something like 
@notification.transaction do
        params[:image_upload].each { |img| @notification.add_image(img) } 
       @notification.save!
      end
return rerender_current_step if @notification.errors.present?

2024-12-19 11:15 UTC, meeravnagesh commented on cosmetics-web/app/controllers/responsible_persons/notifications/product_controller.rb
> +    @notification.transaction do
@notification.transaction do
      model.save_routing_answer(step, form.contains_nanomaterials)
      @notification.make_ready_for_nanomaterials!(form.nanomaterials_count.to_i)
end
render_next_step @notification

shouldnt the code be like this

2024-12-19 11:25 UTC, meeravnagesh commented on cosmetics-web/app/controllers/responsible_persons/notifications/product_controller.rb
> +    @notification.transaction do
@notification.make_single_ready_for_components!(form.components_count.to_i) is this saving something to database

2024-12-19 11:27 UTC, meeravnagesh commented on cosmetics-web/spec/controllers/responsible_persons/notifications/product_controller_spec.rb
> +        ActiveRecord::Base.connection.clear_query_cache
ActiveRecord::Base.connection.clear_query_cache whys is this needed?

2024-12-19 14:57 UTC, mirotriad commented on cosmetics-web/app/controllers/responsible_persons/notifications/product_controller.rb
> +        @notification.update_column(:industry_reference, nil)
Yes, this is needed for data consistency it improves both data integrity and user experience:
- If a user previously selected "yes" and entered a reference, then later changes their mind and selects "no", we need to clear out the old reference so it doesn't linger in the database.
- Without this, we could end up with inconsistent data where the user's answer is "no" but there's still an old reference stored, i.e. if a user later returns to this step, they shouldn't see an old reference when they previously selected "yes".

2024-12-20 13:06 UTC, mirotriad commented on cosmetics-web/app/controllers/responsible_persons/notifications/product_controller.rb
> +    @notification.transaction do
The way you are suggesting would work in the "happy path", but keeping render_next_step inside the transactions provides better error handling and data consistency.

If we move it outside:
- The transaction will rollback
- But we would still try to render the next step
- This could lead to showing the next step with inconsistent data since the previous operations failed

If we keep it inside:
- If any operation fails, the transaction rolls back and the render doesn't happen
- The error handling will catch the failure and handle it appropriately
- This ensures we only proceed to the next step if all operations succeed

2025-01-06 08:58 UTC, mirotriad commented on cosmetics-web/app/controllers/responsible_persons/notifications/product_controller.rb
> +    @notification.transaction do
Yes, it does.
It saves to database when it creates a new component with components.create! and updates the notificaton state through reset_previous_state! and revert_to_details_complete. 

".transaction do" ensures that all database operations succeed or fail together.

2025-01-06 09:06 UTC, mirotriad commented on cosmetics-web/spec/controllers/responsible_persons/notifications/product_controller_spec.rb
> +        ActiveRecord::Base.connection.clear_query_cache
Because: 
- Rails maintains a query cache during requests
- Without clearing it, subsequent identical queries might not hit the database
- For performance testing, we want to measure actual database queries
- Clearing ensures we get accurate count of database operations

Without clearing the cache:
- The second perform_update_request might use cached results
- This would make it appear fewer queries were executed than actually would be in production
- The performance test would give false positives

2025-01-06 12:06 UTC, meeravnagesh commented on cosmetics-web/app/controllers/responsible_persons/notifications/product_controller.rb
> +  before_action :check_notification_submitted
hopefully last question :  why so we need to check if the Notification is submitted

2025-01-06 12:57 UTC, mirotriad commented on cosmetics-web/app/controllers/responsible_persons/notifications/product_controller.rb
> +  before_action :check_notification_submitted
This is to prevent users from modifying notifications that have already been submitted.

2025-01-06 16:12 UTC, meeravnagesh approved these changes

2025-01-06 16:21 UTC, merged